# Generated by Django 4.2.4 on 2023-08-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.AddField(
            model_name='customuser',
            name='department_type',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('ADMIN', 'Administrator'), ('MGMNT', 'Management')], default='AGENT', max_length=14),
        ),
    ]
