# Generated by Django 4.2.4 on 2023-08-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_agent_alter_tour_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='name',
            field=models.CharField(default='s', max_length=50),
            preserve_default=False,
        ),
    ]
