# Generated by Django 4.2.4 on 2023-08-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_agent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='name',
        ),
    ]
